### ISSUE TITLE
Ответные действия со стороны универа

### ISSUE THREAD

**Issue by klonwar** [IchinichiQ/AttendanceCheckBypass#2]
Пожалуйста, сделай репозиторий приватным, если планируешь обновлять скрипт. Админы мудла уже начали писать защиту какую-то. Лучше не усложнять студентам жизнь) Кому надо - тот найдет

**Comment by IchinichiQ** [comment]
> Пожалуйста, сделай репозиторий приватным, если планируешь обновлять скрипт

Репозиторий всегда будет открытым, это моя позиция. Абузить втихаря - неинтересно.

> Админы мудла уже начали писать защиту какую-то

На каждый замок найдется своя отмычка.

**Comment by a1tSignature** [comment]
Какой замок, ты че? Ты приведешь лишь к тому, что придумают что-то посложнее простейшей кнопки, на которую и время тратить не нужно. Усложнить жизнь себе охота, не пойму?

**Comment by IchinichiQ** [comment]
> Ты приведешь лишь к тому, что придумают что-то посложнее простейшей кнопки, на которую и время тратить не нужно

Ты серьезно думаешь, что могут ввести что-то сложнее кнопки, да еще и на которое придется тратить время? Задачку с решением на листочке что-ли?)
Если админы мудла введут меру, которая будет неудобна юзерам - это их проблема. Причем серьезная. Там все таки не совсем идиоты сидят, которые могут допустить это.

**Comment by a1tSignature** [comment]
> > Ты приведешь лишь к тому, что придумают что-то посложнее простейшей кнопки, на которую и время тратить не нужно
> 
> Ты серьезно думаешь, что могут ввести что-то сложнее кнопки, да еще и на которое придется тратить время? Задачку с решением на листочке что-ли?) Если админы мудла введут меру, которая будет неудобна юзерам - это их проблема. Причем серьезная. Там все таки не совсем идиоты сидят, которые могут допустить это.

Ты че, застрял в мире корпоративных приложений? Это образовательная платформа на дистант, она не должна быть удобной, а обязана контролировать процесс того, что дебил на студне не будет прошляпивать пары и заниматься аналогично очке. И не надо считать других людей идиотами, если сам не можешь придумать лучшего решения, чем кнопка. Одумайся, не усложняй ни себе, ни мне жизнь и помести в приватку репу, зачем создавать лишние проблемы?

**Comment by klonwar** [comment]
К сожалению, админам мудла плевать на удобство пользователей. И эта серьезная проблема будет все таки наша.

**Comment by IchinichiQ** [comment]
> Это образовательная платформа на дистант, она не должна быть удобной, а обязана контролировать процесс того, что дебил на студне не будет прошляпивать пары и заниматься аналогично очке.

Прям вижу как на очной лекции ходит подготовленный человек, который просит каждого нажать на кнопочку, ага. А попробуй представить "что-то сложнее") С этим невозможно бороться ни очно, ни дистанционно.
Это борьба с ветряными мельницами, которой всерьез заниматься не будут. Кинули окно с кнопкой, и достаточно.

> К сожалению, админам мудла плевать на удобство пользователей. И эта серьезная проблема будет все таки наша.

Я даже представить себе в реальности эту серьезную проблему не могу. Ну вот правда, что они могут ввести такого страшного, что вы боитесь?
Если они и будут бороться с этим скриптом, то программными путями, к примеру усложнением парса кнопки. Обычных пользователей это не затронет, но тех, кто пользуется скриптом - да.

Единственная причина, по которой стоит сделать приватным репозиторий - это желание держать абуз работоспособным максимальное время. Как я понимаю, это и есть ваша причина.

**Comment by klonwar** [comment]
Разумеется, это и есть причина. Скрипт можно распространять через личные сообщения людям, в которых уверен, и которые не допустят утечки. Но это моя позиция, как понимаю, ты считаешь иначе. Не думаю, что есть смысл спорить. Надеюсь, все-таки до действительно чего-то сложного дело не дойдет
